# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = "http://localhost:1313"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"
enableRobotsTXT = true ## set to true to enable inbuilt robots.txt

#[languages]
#  [languages.en]
#    title = 'CHANGE ME'
#    [languages.en.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 1
#  [languages.fr]
#    title = 'CHANGE ME(FR)'
#    [languages.fr.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3
 
languageCode = "en-us"

title = "Sandy's Stories"
enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "idk"
enableEmoji = true

#[services]
#  [services.disqus]
#    shortname = ''
#  [services.googleAnalytics]
#    id = ''

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "Lindsay Smith"
  about = "Lindsay Smith"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "Lindsay Smith"
  # images = [""]
  themeColor = "#0E1A01"
  accentColor = "#f2f7eb"

  homeSubtitle = "CHANGE ME HOME SUBTITLE"
  #footerCopyright = "COPYRIGHT"
  # footerHideThemeName = false
  # bgImg = ""
  gitUrl = "https://github.com/smithlindsay/website.git"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = true
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  
  [[params.socialLinks]]
    #name = "mastodon"
    #url = "https://joinmastodon.org/"

  [[params.socialLinks]]
    name = "x"
    url = "https://www.twitter.com/LindsayMSmith3"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/smithlindsay"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lindsaymsmith3"

  [[params.socialLinks]]
     name = "google scholar"
     url = "https://scholar.google.com/citations?user=esfG40YAAAAJ&hl=en"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20
